### ISSUE TITLE
[FEA] Add an `update-version.sh`

### ISSUE THREAD

**Issue by brandon-b-miller** [rapidsai/pynvjitlink#26]
Like other RAPIDS repos, it would be nice to have a script that bumps the patch version in the three places it's hardcoded:

https://github.com/rapidsai/pynvjitlink/blob/main/CMakeLists.txt#L5
https://github.com/rapidsai/pynvjitlink/blob/main/pynvjitlink/VERSION#L1
https://github.com/rapidsai/pynvjitlink/blob/main/pyproject.toml#L14

Concretely `update_version.sh` should `+=` the patch version in these three places and possibly remind the user the commit the result.

**Comment by jakirkham** [comment]
Done in PR ( https://github.com/rapidsai/pynvjitlink/pull/44 )
