### ISSUE TITLE
[DOC] Broken link in readme

### ISSUE THREAD

**Issue by msarahan** [rapidsai/pynvjitlink#59]
## Report incorrect documentation

https://docs.nvidia.com/cuda/nvJitLink/index.html is broken

**Location of incorrect documentation**

https://github.com/rapidsai/pynvjitlink/blob/main/README.md?plain=1#L4

**Describe the problems or issues found in the documentation**
A clear and concise description of what you found to be incorrect.

**Steps taken to verify documentation is incorrect**
List any steps you have taken:

**Suggested fix for documentation**
Detail proposed changes to fix the documentation if you have any.

---

## Report needed documentation

**Report needed documentation**
A clear and concise description of what documentation you believe it is needed and why.

**Describe the documentation you'd like**

**Steps taken to search for needed documentation**
List any steps you have taken:

**Comment by wence-** [comment]
Correct link is https://docs.nvidia.com/cuda/nvjitlink/index.html (all lowercase)

**Comment by jakirkham** [comment]
This was fixed in PR: https://github.com/rapidsai/pynvjitlink/pull/61
