### ISSUE TITLE
Is `.ycm_extra_conf.py` needed?

### ISSUE THREAD

**Issue by jakirkham** [rapidsai/pynvjitlink#63]
Am seeing this file `.ycm_extra_conf.py` and am wondering if it is needed

It appears to use CUDA 12.0 headers (not sure if that is expected)

https://github.com/rapidsai/pynvjitlink/blob/72a76ee544f0f6a8b3e28f7d1e8f1260175a609c/.ycm_extra_conf.py#L14

Also pins to Python 3.10 headers

https://github.com/rapidsai/pynvjitlink/blob/72a76ee544f0f6a8b3e28f7d1e8f1260175a609c/.ycm_extra_conf.py#L9

If this file is still needed, maybe it could benefit from some cleanup

If not, maybe we can just drop it

Note: It appears [the file is not used in the repo]( https://github.com/search?q=repo%3Arapidsai%2Fpynvjitlink+%22.ycm_extra_conf.py%22&type=code )

**Comment by vyasr** [comment]
`.ycm_extra_conf.py` is a config file used by https://github.com/ycm-core/YouCompleteMe, a vim plugin for semantic completion and similar things. I'm guessing @gmarkall makes use of it for his local development since he committed the file initially, so I'm curious to hear if he wants to keep it for some reason.

**Comment by jakirkham** [comment]
Thanks for the context! 🙏

Agree it would be great to hear from Graham 🙂

**Comment by gmarkall** [comment]
I think it helps anyone using YCM. The hardcoded paths need to be fixed though, I'll submit a PR once I've finished tidying up #60.

**Comment by jakirkham** [comment]
Thanks Graham! 🙏

In that case, what about something like this: https://github.com/rapidsai/pynvjitlink/pull/64 ?

Open to feedback there

**Comment by jakirkham** [comment]
A more generalized approach is in PR: https://github.com/rapidsai/pynvjitlink/pull/65

Feel free to merge whichever works best 🙂
